### ISSUE TITLE
example of private keys

### ISSUE THREAD

**Issue by dolphinsd** [google-pay/payment-data-cryptography-dotnet#8]
Hi, we obtained json file from developer console for our service account.

How we generate, extract private key from json file provided by google?

Pasting private key from json file does not seems to work in step parser.AddPrivateKey.

**Comment by sajasbana** [comment]
@dolphinsd 
did it worked with you?
I'm trying save values from google doc but not working

**Comment by fstanis** [comment]
Please refer to [Payment data cryptography](https://developers.google.com/pay/api/web/guides/resources/payment-data-cryptography) for information about generating keys and the protocol itself.
